<a href="https://colab.research.google.com/github/rajanpandi/dvd_data/blob/main/final_project_genere_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/combine1_data.csv")

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
df.head(3)

category_id    name  film_id        title  \
0         11.0  Horror    749.0  Rules Human   
1         11.0  Horror    749.0  Rules Human   
2         11.0  Horror    749.0  Rules Human   

                                         description  release_year  \
0  A Beautiful Epistle of a Astronaut And a Stude...        2006.0   
1  A Beautiful Epistle of a Astronaut And a Stude...        2006.0   
2  A Beautiful Epistle of a Astronaut And a Stude...        2006.0   

   language_id  rental_duration  rental_rate  length  replacement_cost rating  \
0          1.0              6.0         4.99   153.0             19.99      R   
1          1.0              6.0         4.99   153.0             19.99      R   
2          1.0              6.0         4.99   153.0             19.99      R   

   inventory_id  store_id  rental_id          rental_date  customer_id  \
0        3419.0       1.0     1520.0  2005-06-15 23:57:20        341.0   
1        3419.0       1.0     1520.0  2005-06-15 23:57:20        341.0   
2        3419.0       1.0     1520.0  2005-06-15 23:57:20        341.0   

           return_date  staff_id  amount  payment_id  \
0  2005-06-24 23:46:20       1.0    7.99     17503.0   
1  2005-06-24 23:46:20       1.0    7.99     17503.0   
2  2005-06-24 23:46:20       1.0    7.99     17503.0   

                 payment_date  actor_id first_name    last_name  \
0  2007-02-15 22:25:46.996577     161.0     Harvey         Hope   
1  2007-02-15 22:25:46.996577     127.0      Kevin      Garland   
2  2007-02-15 22:25:46.996577      77.0       Cary  Mcconaughey   

                 name-2  
0  English               
1  English               
2  English

In [5]:
df=df[["name","description","actor_id"]]

In [53]:
df["description"][150]

'A Emotional Epistle of a Squirrel And a Robot who must Confront a Lumberjack in Soviet Georgia'

In [6]:
df.head(3)

name                                        description  actor_id
0  Horror  A Beautiful Epistle of a Astronaut And a Stude...     161.0
1  Horror  A Beautiful Epistle of a Astronaut And a Stude...     127.0
2  Horror  A Beautiful Epistle of a Astronaut And a Stude...      77.0

In [7]:
df.isnull().sum()

name            5
description     5
actor_id       45
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.name.unique()

array(['Horror', 'Documentary', 'New', 'Classics', 'Games', 'Sci-Fi',
       'Foreign', 'Family', 'Travel', 'Music', 'Sports', 'Comedy',
       'Drama', 'Action', 'Children', 'Animation'], dtype=object)

In [10]:
assign={'Horror':1, 'Documentary':2, 'New':3, 'Classics':4, 'Games':5, 'Sci-Fi':6,
       'Foreign':7, 'Family':8, 'Travel':9, 'Music':10, 'Sports':11, 'Comedy':12,
       'Drama':13, 'Action':14, 'Children':15, 'Animation':16}

In [11]:
df["name"]=df["name"].map(assign)

In [12]:
df.shape

(88230, 3)

In [13]:
df.description.nunique()

997

In [14]:
df.head(3)

name                                        description  actor_id
0     1  A Beautiful Epistle of a Astronaut And a Stude...     161.0
1     1  A Beautiful Epistle of a Astronaut And a Stude...     127.0
2     1  A Beautiful Epistle of a Astronaut And a Stude...      77.0

In [15]:
df.duplicated().sum()

82768

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.duplicated().sum()

0

In [18]:
df.shape

(5462, 3)

In [19]:
df.isnull().sum()

name           0
description    0
actor_id       0
dtype: int64

In [20]:
df.description.nunique()

997

In [21]:
df.actor_id.nunique()

200

In [22]:
df.name.nunique()

16

In [23]:
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [25]:
courpus=[]

In [26]:
df["description"][0]

'A Beautiful Epistle of a Astronaut And a Student who must Confront a Monkey in An Abandoned Fun House'

In [27]:
re.sub(pattern='[^a-zA-Z]',repl=' ',string=df["description"][0])

'A Beautiful Epistle of a Astronaut And a Student who must Confront a Monkey in An Abandoned Fun House'

In [28]:
re.sub(pattern='[^a-zA-Z]',repl=' ',string=df["description"][0]).lower()

'a beautiful epistle of a astronaut and a student who must confront a monkey in an abandoned fun house'

In [29]:
df.shape[0]

5462

In [30]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# Download NLTK stopwords if not already installed
nltk.download('stopwords')

ps = PorterStemmer()
corpus = []

for i in range(0, df.shape[0]):
    # Use iloc to access the row by position, not by index
    text = re.sub(pattern='[^a-zA-Z]', repl=' ', string=df["description"].iloc[i])
    text = text.lower()  # Convert to lowercase
    words = text.split()  # Split into words
    # Remove stopwords
    clean_words = [word for word in words if word not in set(stopwords.words("english"))]
    # Apply stemming
    stemmed_words = [ps.stem(word) for word in clean_words]
    # Join the words back into a single string
    text = " ".join(stemmed_words)
    corpus.append(text)

# Now the 'corpus' contains the cleaned, lowercased, and stemmed text.


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10000,ngram_range=(1,2))
x=cv.fit_transform(corpus).toarray()
y=df["name"].values


In [32]:
from keras.utils import to_categorical #one hot encoder in sklearn preprocessing

y =to_categorical(y)
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [33]:
x.shape,y.shape

((5462, 2584), (5462, 17))

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
model = Sequential()
#input dimension 8 neuron - developer scope
model.add(Dense(512,input_dim = x_train.shape[1],activation='tanh')) #hidden layer1
model.add(Dense(512,activation='tanh')) #hidden layer2
model.add(Dense(256,activation='tanh')) #hidden layer3
model.add(Dense(128,activation='tanh')) #hidden layer3
model.add(Dense(64,activation='tanh')) #hidden layer3
model.add(Dense(64,activation='tanh')) #hidden layer3
model.add(Dense(32,activation='tanh')) #hidden layer3
model.add(Dense(32,activation='tanh')) #hidden layer3

model.add(Dense(17,activation="softmax")) #output layer
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=[tf.keras.metrics.F1Score(),"accuracy",tf.keras.metrics.Precision(),tf.keras.metrics.Recall()])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
result = model.fit(x_train, y_train, epochs=25, validation_split=0.2, batch_size=2)

Epoch 1/25
1748/1748 ━━━━━━━━━━━━━━━━━━━━ 48s 25ms/step - accuracy: 0.1119 - f1_score: 0.0844 - loss: 2.7812 - precision: 0.0000e+00 - recall: 0.0000e+00 - val_accuracy: 0.1419 - val_f1_score: 0.0790 - val_loss: 2.5964 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 2/25
1748/1748 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.2006 - f1_score: 0.1447 - loss: 2.4002 - precision: 0.0440 - recall: 6.2524e-05 - val_accuracy: 0.2563 - val_f1_score: 0.1775 - val_loss: 2.2584 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00
Epoch 3/25
1748/1748 ━━━━━━━━━━━━━━━━━━━━ 42s 20ms/step - accuracy: 0.2994 - f1_score: 0.2339 - loss: 2.0409 - precision: 0.3682 - recall: 0.0099 - val_accuracy: 0.3467 - val_f1_score: 0.2854 - val_loss: 1.9598 - val_precision: 0.5556 - val_recall: 0.0458
Epoch 4/25
1748/1748 ━━━━━━━━━━━━━━━━━━━━ 40s 19ms/step - accuracy: 0.4484 - f1_score: 0.3878 - loss: 1.6740 - precision: 0.5729 - recall: 0.1264 - val_accuracy: 0.4554 - val_f1_score: 0.3985 - val_loss: 

In [37]:
model.evaluate(x_test,y_test)

35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9279 - f1_score: 0.8683 - loss: 0.4411 - precision: 0.9470 - recall: 0.9194


[0.4672519266605377,
 <tf.Tensor: shape=(17,), dtype=float32, numpy=
 array([0.        , 0.9242424 , 0.9104477 , 0.92397654, 0.9291338 ,
        0.87999994, 0.8932038 , 0.9213483 , 0.92517   , 0.9104477 ,
        0.94915247, 0.97802186, 0.88188964, 0.9606299 , 0.9166666 ,
        0.91935486, 0.8985506 ], dtype=float32)>,
 0.9222323894500732,
 0.9397363662719727,
 0.9130832552909851]

In [38]:
yp=model.predict(x_test)
yp[:1]

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


array([[1.24939614e-08, 1.57881350e-05, 1.69415958e-04, 8.46326910e-03,
        1.27628329e-04, 2.94653350e-03, 8.25575335e-05, 9.73966777e-01,
        4.48214216e-03, 2.13415315e-03, 3.27249436e-05, 2.23770738e-04,
        1.12782516e-04, 1.21394369e-05, 4.60081137e-05, 5.84984446e-06,
        7.17849890e-03]], dtype=float32)

In [39]:

df4 = pd.DataFrame(yp)

# Find the index of the column with the maximum value (nearest to 1)
max_index = df4.idxmax(axis=1)

# Create a new DataFrame where the max column is set to 1 and others to 0
output_df = pd.DataFrame(0, index=df.index, columns=df4.columns)  # Create a DataFrame filled with 0s
output_df.values[np.arange(len(max_index)), max_index] = 1  # Set the max column to 1

# Display the result
output_df[:5]

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0
1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
3   0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0
4   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0

In [40]:
y_test[:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.]])

In [41]:
model.save("my_model.h5")

In [49]:
import pickle

# Assuming cv is your CountVectorizer after fitting on training data
with open('count_vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)


In [42]:
pip install streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 90.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 90.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.9/82.9 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 5.5 MB/s eta 0:00:00
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.0.0
    Uninstalling tenacity-9.0.0:
      Successfully uninstalled tenacity-9.0.0


In [47]:
!wget -q -O - ipv4.icanhazip.com

34.145.173.53


In [ ]:
! streamlit run app.py & npx localtunnel --port 8501




  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.2:8501
  External URL: http://34.145.173.53:8501

your url is: https://proud-keys-move.loca.lt
2024-10-01 17:24:45.327412: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-01 17:24:45.355946: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-01 17:24:45.364597: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-01 17:24:46.804667: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[nltk_data] Downloadi